service: appsync-example

plugins:
  - serverless-appsync-plugin
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  graphql:
    handler: handler.graphqlHandler

custom:
  appSync:
    authenticationType: API_KEY
    mappingTemplates:
      - dataSource: Users
        type: Query
        field: getUserInfo
        request: 'getUserInfo-request-mapping-template.vtl'
        response: 'getUserInfo-response-mapping-template.vtl'
      - dataSource: Lambda_MeInfo
        type: Query
        field: meInfo
        request: 'meInfo-request-mapping-template.vtl'
        response: 'meInfo-response-mapping-template.vtl'
      - dataSource: ElasticSearch
        type: Query
        field: searchAllTweetsByKeyword
        request: 'searchAllTweetsByKeyword-request-mapping-template.vtl'
        response: 'searchAllTweetsByKeyword-response-mapping-template.vtl'
      - dataSource: Tweets
        type: User
        field: topTweet
        request: 'topTweet-request-mapping-template.vtl'
        response: 'topTweet-response-mapping-template.vtl'
      - dataSource: Tweets
        type: User
        field: tweets
        request: 'tweets-request-mapping-template.vtl'
        response: 'tweets-response-mapping-template.vtl'
      - dataSource: Tweets
        type: Mutation
        field: createTweet
        request: 'createTweet-request-mapping-template.vtl'
        response: 'createTweet-response-mapping-template.vtl'
      - dataSource: Tweets
        type: Mutation
        field: deleteTweet
        request: 'deleteTweet-request-mapping-template.vtl'
        response: 'deleteTweet-response-mapping-template.vtl'
      - dataSource: Tweets
        type: Mutation
        field: reTweet
        request: 'reTweet-request-mapping-template.vtl'
        response: 'reTweet-response-mapping-template.vtl'
      - dataSource: Tweets
        type: Mutation
        field: updateTweet
        request: 'updateTweet-request-mapping-template.vtl'
        response: 'updateTweet-response-mapping-template.vtl'
      - dataSource: Users
        type: Mutation
        field: updateUserInfo
        request: 'updateUserInfo-request-mapping-template.vtl'
        response: 'updateUserInfo-response-mapping-template.vtl'
    # schema: # defaults schema.graphql
    dataSources:
      - type: AMAZON_DYNAMODB
        name: Users
        description: 'Users table'
        config:
          tableName: { Ref: UserTable }
          serviceRoleArn: { Fn::GetAtt: [AppSyncDynamoDBServiceRole, Arn] }
      - type: AMAZON_DYNAMODB
        name: Tweets
        description: 'Tweets table'
        config:
          tableName: { Ref: TweetsTable }
          serviceRoleArn: { Fn::GetAtt: [AppSyncDynamoDBServiceRole, Arn] }
      - type: AMAZON_ELASTICSEARCH
        name: ElasticSearch
        description: 'ElasticSearch'
        config:
          endpoint: # required # "https://{DOMAIN}.{REGION}.es.amazonaws.com"
          serviceRoleArn: { Fn::GetAtt: [AppSyncESServiceRole, Arn] }
      - type: AWS_LAMBDA
        name: Lambda_MeInfo
        description: 'Lambda DataSource'
        config: # Either of functionName or lambdaFunctionArn must tbe provided. When both are present, lambdaFunctionArn is used.
          functionName: graphql
          lambdaFunctionArn: { Fn::GetAtt: [GraphqlLambdaFunction, Arn] } #
          serviceRoleArn: { Fn::GetAtt: [AppSyncLambdaServiceRole, Arn] }

resources:
  Resources:
    UserTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        KeySchema:
          - AttributeName: handle
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: handle
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'Users'
    TweetsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        KeySchema:
          - AttributeName: tweet_id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: tweet_id
            AttributeType: S
          - AttributeName: handle
            AttributeType: S
          - AttributeName: retweet_count
            AttributeType: N
          - AttributeName: created_at
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'Tweets'
        GlobalSecondaryIndexes:
          - IndexName: top-index
            KeySchema:
              - AttributeName: handle
                KeyType: HASH
              - AttributeName: retweet_count
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: tweet-index
            KeySchema:
              - AttributeName: handle
                KeyType: HASH
              - AttributeName: created_at
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
